name: Jest Tests

on:
  push:
    branches: [main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main]

jobs:
  build:
    name: Jest Unit Testing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
    - uses: actions/checkout@v2 
    - name: Run Jest  
    uses: actions/setup-node@v1
    # - uses: stefanoeb/jest-action@1.0.3
    - run: npm test